export const CART_ADD_ITEM = "CART_ADD_ITEM";


export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAIL = "CART_REMOVE_ITEM_FAIL";

export const CART_INFO_REQUEST = "CART_INFO_REQUEST";
export const CART_INFO_SUCCESS = "CART_INFO_SUCCESS";
export const CART_INFO_FAIL = "CART_INFO_FAIL";


export const CART_EMPTY = "CART_EMPTY";

