export const PAY_SELECT_METHOD_TR_REQUEST = "PAY_SELECT_METHOD_TR_REQUEST";
export const PAY_SELECT_METHOD_TR_SUCCESS = "PAY_SELECT_METHOD_TR_SUCCESS";
export const PAY_SELECT_METHOD_TR_FAIL = "PAY_SELECT_METHOD_TR_FAIL";

export const PAY_SELECT_METHOD_CB_REQUEST = "PAY_SELECT_METHOD_CB_REQUEST";
export const PAY_SELECT_METHOD_CB_SUCCESS = "PAY_SELECT_METHOD_CB_SUCCESS";
export const PAY_SELECT_METHOD_CB_FAIL = "PAY_SELECT_METHOD_CB_FAIL";

export const GET_PM_REQUEST = "PM_REQUEST";
export const GET_PM_SUCCESS = "GET_PM_SUCCESS";
export const GET_PM_FAIL = "GET_PM_FAIL";