export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const ADD_USER_ID_REQUEST = "ADD_USER_ID_REQUEST";
export const ADD_USER_ID_SUCCESS = "ADD_USER_ID_SUCCESS";
export const ADD_USER_ID_FAIL = "ADD_USER_ID_FAIL";